when:
  - event: push
    branch: main
    path:
      include:
        - webapp/**

steps:
  - name: deploy
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - |
        set -e
        cd webapp
        docker compose -p prg381 build --no-cache
        docker compose -p prg381 down
        docker compose -p prg381 up
